version: '3'

networks:
  laravel_wwdtracker:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_wwdtracker
    ports: 
      - "8101:80"
      - "43101:443"
    volumes: 
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel_wwdtracker
  mysql:
    image: arm64v8/mariadb
    container_name: mysql_wwdtracker
    restart: unless-stopped
    tty: true
    ports: 
      - "33101:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: wwdtracker
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      DERVICE_NAME: mysql
    networks:
      - laravel_wwdtracker
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_wwdtracker
    volumes: 
      - ../:/var/www
    ports: 
      - "9101:9000"
    networks:
      - laravel_wwdtracker